"""Render MLPilot roadmap issues and (optionally) create them on GitHub.

    python3 build.py                 # writes ISSUES.md (no network)
    python3 build.py --create        # creates labels + issues with the GitHub CLI (gh auth login first)
    python3 build.py --create --dry  # prints what it would do

Idempotent: issues whose exact title already exists are skipped, and their numbers reused.
References like "#1.2" in issue text are rewritten to the real issue numbers.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

from issues_data import ISSUES, LABELS, REPO, ROADMAP_BODY

HERE = Path(__file__).parent
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
ROADMAP_TITLE = "[Roadmap] MLPilot: prediction agent for your own database (tracking issue)"


def title(i):
    return f"[{i['id']}] {i['title']}"


def labels(i):
    return [i["priority"], f"phase-{i['phase']}", *[f"area:{a}" for a in i["areas"]], f"type:{i['type']}"]


def body(i, numbers=None, roadmap_no=None):
    def ref(m):
        key = m.group(1)
        if numbers and key in numbers:
            return f"#{numbers[key]}"
        return f"[{key}]"

    parts = ["## Context", i["context"]]
    if i["files"]:
        parts += ["## Files", "\n".join(f"- `{f}`" if "(" not in f else f"- {f}" for f in i["files"])]
    parts += ["## What to do", "\n".join(f"- {t}" for t in i["tasks"])]
    parts += ["## Acceptance criteria", "\n".join(f"- [ ] {a}" for a in i["acceptance"])]
    parts.append("Done means every box above is shown passing in CI or pasted command output, not self-reported.")
    if i["refs"]:
        parts += ["## References", "\n".join(f"- {r}" for r in i["refs"])]
    deps = ", ".join(f"#{d}" for d in i["depends"]) if i["depends"] else "nothing"
    parts += ["## Depends on", deps]
    meta = f"Priority **{i['priority']}** · Phase **{i['phase']}**"
    if roadmap_no:
        meta += f" · Part of #{roadmap_no}"
    parts += ["", meta]
    text = "\n\n".join(parts)
    text = re.sub(r"#(\d+\.\d+)\b", ref, text)
    return text + FOOTER


def write_files():
    lines = ["# MLPilot roadmap issues (draft)", "", f"Repository: {REPO}. {len(ISSUES)} issues + 1 tracking issue.", ""]
    phase = None
    for i in ISSUES:
        if i["phase"] != phase:
            phase = i["phase"]
            lines += ["", f"## Phase {phase}", ""]
        lines.append(f"- **{title(i)}** ({', '.join(labels(i))})")
    lines += ["", "---", ""]
    for i in ISSUES:
        lines += [f"## {title(i)}", "", f"Labels: {', '.join(labels(i))}", "", body(i).replace(FOOTER, ""), "", "---", ""]
    (HERE / "ISSUES.md").write_text("\n".join(lines))
    print(f"wrote ISSUES.md ({len(ISSUES)} issues)")


def gh(*args, dry=False):
    if dry:
        print("gh", *args[:4], "...")
        return ""
    return subprocess.run(["gh", *args], check=True, capture_output=True, text=True).stdout


def create(dry):
    for name, color, desc in LABELS:
        gh("label", "create", name, "--repo", REPO, "--color", color, "--description", desc, "--force", dry=dry)
    existing = {}
    if not dry:
        out = gh("issue", "list", "--repo", REPO, "--state", "all", "--limit", "500", "--json", "number,title")
        existing = {x["title"]: x["number"] for x in json.loads(out)}

    def make(t, b, lbls):
        if t in existing:
            print(f"skip (exists #{existing[t]}): {t}")
            return existing[t]
        args = ["issue", "create", "--repo", REPO, "--title", t, "--body", b]
        for lbl in lbls:
            args += ["--label", lbl]
        url = gh(*args, dry=dry).strip()
        no = int(url.rsplit("/", 1)[-1]) if url else 0
        print(f"created #{no}: {t}")
        return no

    roadmap_no = make(ROADMAP_TITLE, ROADMAP_BODY + "\n\n## Issues\n\n(filled in below)" + FOOTER, ["type:tracking", "P0"])
    numbers = {}
    for i in ISSUES:
        numbers[i["id"]] = make(title(i), body(i, numbers, roadmap_no), labels(i))

    listing, phase = [], None
    for i in ISSUES:
        if i["phase"] != phase:
            phase = i["phase"]
            listing.append(f"\n**Phase {phase}**\n")
        listing.append(f"- [ ] #{numbers[i['id']]} {title(i)} ({i['priority']})")
    gh("issue", "edit", str(roadmap_no), "--repo", REPO, "--body",
       ROADMAP_BODY + "\n## Issues\n" + "\n".join(listing) + FOOTER, dry=dry)
    print("tracking issue updated")


if __name__ == "__main__":
    write_files()
    if "--create" in sys.argv:
        create(dry="--dry" in sys.argv)
