-- Generated by generate.py --schema (the schema is defined there). Do not edit.
-- Synthetic e-commerce demo database for MLPilot (issue #47).

CREATE TABLE customers (
    customer_id bigint NOT NULL,
    email text,
    signup_at timestamp NOT NULL,
    country text,
    acquisition_channel text,
    plan text,
    is_churned boolean,
    discount_code_used_after_churn text,
    PRIMARY KEY (customer_id)
);

CREATE TABLE products (
    product_id bigint NOT NULL,
    name text,
    category text,
    price double precision,
    PRIMARY KEY (product_id)
);

CREATE TABLE orders (
    order_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    ordered_at timestamp NOT NULL,
    status text,
    total double precision,
    PRIMARY KEY (order_id),
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE order_items (
    order_item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity bigint,
    unit_price double precision,
    PRIMARY KEY (order_item_id),
    FOREIGN KEY (order_id) REFERENCES orders (order_id),
    FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE TABLE sessions (
    session_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    started_at timestamp NOT NULL,
    device text,
    pages bigint,
    PRIMARY KEY (session_id),
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE support_tickets (
    ticket_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    opened_at timestamp NOT NULL,
    category text,
    resolved_at timestamp,
    satisfaction bigint,
    PRIMARY KEY (ticket_id),
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE refunds (
    refund_id bigint NOT NULL,
    order_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    refunded_at timestamp NOT NULL,
    amount double precision,
    PRIMARY KEY (refund_id),
    FOREIGN KEY (order_id) REFERENCES orders (order_id),
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE marketing_emails (
    email_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    sent_at timestamp NOT NULL,
    opened boolean,
    PRIMARY KEY (email_id),
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE customer_status_snapshot (
    customer_id bigint NOT NULL,
    status text,
    updated_at timestamp NOT NULL,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE INDEX idx_orders_customer_id_ordered_at ON orders (customer_id, ordered_at);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);

CREATE INDEX idx_sessions_customer_id_started_at ON sessions (customer_id, started_at);

CREATE INDEX idx_support_tickets_customer_id_opened_at ON support_tickets (customer_id, opened_at);

CREATE INDEX idx_refunds_order_id ON refunds (order_id);

CREATE INDEX idx_marketing_emails_customer_id_sent_at ON marketing_emails (customer_id, sent_at);
