/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects__get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/agent/auto-optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Auto Optimize
         * @description Start the autonomous optimization loop on one data version.
         */
        post: operations["start_auto_optimize_api_v1_projects__project_id__agent_auto_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/agent/auto-optimize/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auto Optimize
         * @description Poll an auto-optimize job.
         */
        get: operations["get_auto_optimize_api_v1_projects__project_id__agent_auto_optimize__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/chat/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask History
         * @description Answer a question strictly from the project's recorded experiment history.
         */
        post: operations["ask_history_api_v1_projects__project_id__chat_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Sample Dataset
         * @description Load a bundled sample dataset as an immutable version.
         */
        post: operations["load_sample_dataset_api_v1_projects__project_id__datasets_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Snapshot Sql Query
         * @description Run one read-only query and store the result as an immutable version.
         */
        post: operations["snapshot_sql_query_api_v1_projects__project_id__datasets_sql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Dataset
         * @description Upload a CSV, store it as an immutable version and return its columns.
         */
        post: operations["upload_dataset_api_v1_projects__project_id__datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/{data_version_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Columns */
        get: operations["get_columns_api_v1_projects__project_id__datasets__data_version_id__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/{data_version_id}/leakage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leakage */
        get: operations["get_leakage_api_v1_projects__project_id__datasets__data_version_id__leakage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/{data_version_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_projects__project_id__datasets__data_version_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/datasets/{data_version_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Suggestions
         * @description Ask the planner for feature ideas (data only; nothing is run).
         */
        get: operations["get_suggestions_api_v1_projects__project_id__datasets__data_version_id__suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Experiment Tree
         * @description The project's experiments as a flat tree, optionally only those on one data version.
         */
        get: operations["experiment_tree_api_v1_projects__project_id__experiments_get"];
        put?: never;
        /**
         * Run Experiment
         * @description Queue an experiment that adds one suggested feature.
         */
        post: operations["run_experiment_api_v1_projects__project_id__experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments/auto-clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Auto Clean
         * @description Ask the LLM for a cleaning configuration and queue it as a baseline.
         */
        post: operations["run_auto_clean_api_v1_projects__project_id__experiments_auto_clean_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Baseline
         * @description Queue a deterministic baseline without new features.
         */
        post: operations["run_baseline_api_v1_projects__project_id__experiments_baseline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments/champion/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Champion
         * @description Training script of the current champion on one data version.
         */
        get: operations["export_champion_api_v1_projects__project_id__experiments_champion_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_v1_projects__project_id__experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments/{experiment_id}/debrief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debrief
         * @description Plain-language debrief grounded in the recorded metrics and built-in importances.
         *
         *     SHAP is not implemented yet.
         */
        get: operations["debrief_api_v1_projects__project_id__experiments__experiment_id__debrief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/experiments/{experiment_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Experiment
         * @description A standalone Python script that rebuilds the experiment's features and model.
         */
        get: operations["export_experiment_api_v1_projects__project_id__experiments__experiment_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Query */
            query: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Grounding Context */
            grounding_context: string;
        };
        /** AutoOptimizeRequest */
        AutoOptimizeRequest: {
            /** Data Version Id */
            data_version_id: string;
            /**
             * N Hypotheses
             * @default 5
             */
            n_hypotheses: number;
            /** Target Column */
            target_column: string;
        };
        /** Body_upload_dataset_api_v1_projects__project_id__datasets_upload_post */
        Body_upload_dataset_api_v1_projects__project_id__datasets_upload_post: {
            /** File */
            file: string;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Dist */
            dist: number[];
            /**
             * Dtype
             * @enum {string}
             */
            dtype: "int" | "float" | "category" | "datetime" | "bool" | "string";
            /** Missing Pct */
            missing_pct: number;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "feature" | "target" | "id";
            /** Unique */
            unique: number;
        };
        /** DataMetrics */
        DataMetrics: {
            /** Duplicate Rows */
            duplicate_rows: number;
            /** Missing Data Percent */
            missing_data_percent: number;
            /** Total Columns */
            total_columns: number;
            /** Total Rows */
            total_rows: number;
        };
        /**
         * DatasetInfo
         * @description What loading data returns: the stored version and its columns.
         */
        DatasetInfo: {
            /** Columns */
            columns: string[];
            /** Data Version Id */
            data_version_id: string;
            /** Default Target */
            default_target?: string | null;
            /** Filename */
            filename: string;
            /** Short Hash */
            short_hash: string;
            /** Total Rows */
            total_rows: number;
        };
        /** DatasetTargetRequest */
        DatasetTargetRequest: {
            /** Data Version Id */
            data_version_id: string;
            /** Target Column */
            target_column: string;
        };
        /** Debrief */
        Debrief: {
            /** Debrief */
            debrief: string;
            /** Feature Importances */
            feature_importances: {
                [key: string]: number;
            };
            /** Importance Method */
            importance_method: string;
        };
        /**
         * ExperimentDecision
         * @enum {string}
         */
        ExperimentDecision: "keep" | "reject" | "inconclusive" | "pending";
        /**
         * ExperimentNode
         * @description One experiment as the UI's experiment tree shows it.
         */
        ExperimentNode: {
            /** Champion */
            champion: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Version Id */
            data_version_id: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "keep" | "reject" | "baseline" | "none";
            /** Error */
            error: string | null;
            /** Feature */
            feature: string | null;
            /**
             * Hypothesis Mode
             * @description 'fallback' when the idea came from the offline stub, not a real LLM
             */
            hypothesis_mode?: string | null;
            /** Id */
            id: string;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
            /** Model Name */
            model_name: string;
            /** On Champion Path */
            on_champion_path: boolean;
            /** Parent Id */
            parent_id: string | null;
            /** Runtime Seconds */
            runtime_seconds: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** ExperimentRead */
        ExperimentRead: {
            /** Agent Model */
            agent_model?: string | null;
            /**
             * Artifacts
             * @default []
             */
            artifacts: string[];
            /**
             * Budget
             * @default {}
             */
            budget: {
                [key: string]: number;
            };
            /** Change Description */
            change_description: string;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Version Id */
            data_version_id?: string | null;
            /** Dataset Version */
            dataset_version: string;
            /** @default pending */
            decision: components["schemas"]["ExperimentDecision"];
            /** Decision Reason */
            decision_reason?: string | null;
            /**
             * Feature Set
             * @default []
             */
            feature_set: string[];
            /** Hypothesis */
            hypothesis: string;
            /** Id */
            id: string;
            /** Metrics */
            metrics?: {
                [key: string]: number | null;
            } | null;
            /** Model Name */
            model_name: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: unknown;
            };
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Preprocessing Config
             * @default {}
             */
            preprocessing_config: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: string;
            /** Runtime Seconds */
            runtime_seconds?: number | null;
            /** @default created */
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Validation Config
             * @default {}
             */
            validation_config: {
                [key: string]: unknown;
            };
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "created" | "validated" | "queued" | "running" | "completed" | "failed" | "rejected_invalid";
        /** ExportScript */
        ExportScript: {
            /** Experiment Id */
            experiment_id: string;
            /** Filename */
            filename: string;
            /** Script */
            script: string;
        };
        /** FeatureSuggestion */
        FeatureSuggestion: {
            /**
             * Availability Assumption
             * @default
             */
            availability_assumption: string;
            /** Formula */
            formula: string;
            /**
             * Llm
             * @description Provider, model, cost and decision_mode of the call that proposed it
             */
            llm?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Required Columns */
            required_columns?: string[];
            /**
             * Risk
             * @default
             */
            risk: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Error */
            error?: string | null;
            /** Job Id */
            job_id: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed";
        };
        /** LeakageFinding */
        LeakageFinding: {
            /** Category */
            category: string;
            /** Check */
            check: string;
            /** Column */
            column: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
        };
        /** PaginatedResponse[ProjectRead] */
        PaginatedResponse_ProjectRead_: {
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            task_type: components["schemas"]["TaskType"];
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Owner Id */
            owner_id: string;
            status: components["schemas"]["ProjectStatus"];
            task_type: components["schemas"]["TaskType"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived" | "completed";
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /** RunExperimentRequest */
        RunExperimentRequest: {
            /** Data Version Id */
            data_version_id: string;
            feature_suggestion?: components["schemas"]["SuggestionIn"];
            /** Model Name */
            model_name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Target Column */
            target_column: string;
        };
        /** SampleDatasetRequest */
        SampleDatasetRequest: {
            /**
             * Dataset Name
             * @default telecom_churn
             */
            dataset_name: string;
        };
        /** SqlSnapshotRequest */
        SqlSnapshotRequest: {
            /**
             * Connection String
             * @description Read-only connection; never stored or echoed
             */
            connection_string: string;
            /** Query */
            query: string;
        };
        /** SuggestionIn */
        SuggestionIn: {
            /** Formula */
            formula?: string | null;
            /** Name */
            name?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "binary_classification" | "multiclass_classification" | "regression";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_projects_api_v1_projects__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ProjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_auto_optimize_api_v1_projects__project_id__agent_auto_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoOptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auto_optimize_api_v1_projects__project_id__agent_auto_optimize__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_history_api_v1_projects__project_id__chat_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_sample_dataset_api_v1_projects__project_id__datasets_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_sql_query_api_v1_projects__project_id__datasets_sql_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_v1_projects__project_id__datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_projects__project_id__datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_columns_api_v1_projects__project_id__datasets__data_version_id__columns_get: {
        parameters: {
            query: {
                target_column: string;
            };
            header?: never;
            path: {
                data_version_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnProfile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leakage_api_v1_projects__project_id__datasets__data_version_id__leakage_get: {
        parameters: {
            query: {
                target_column: string;
            };
            header?: never;
            path: {
                data_version_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeakageFinding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_projects__project_id__datasets__data_version_id__metrics_get: {
        parameters: {
            query: {
                target_column: string;
            };
            header?: never;
            path: {
                data_version_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggestions_api_v1_projects__project_id__datasets__data_version_id__suggestions_get: {
        parameters: {
            query: {
                target_column: string;
                user_query?: string | null;
            };
            header?: never;
            path: {
                data_version_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_tree_api_v1_projects__project_id__experiments_get: {
        parameters: {
            query?: {
                data_version_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_experiment_api_v1_projects__project_id__experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_auto_clean_api_v1_projects__project_id__experiments_auto_clean_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetTargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_baseline_api_v1_projects__project_id__experiments_baseline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetTargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_champion_api_v1_projects__project_id__experiments_champion_export_get: {
        parameters: {
            query: {
                data_version_id: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportScript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_v1_projects__project_id__experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debrief_api_v1_projects__project_id__experiments__experiment_id__debrief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Debrief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_experiment_api_v1_projects__project_id__experiments__experiment_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportScript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
