"""Alembic owns the metadata DB schema: fresh upgrade/downgrade, data kept, models match."""

from __future__ import annotations

import sqlite3
from datetime import UTC, datetime
from pathlib import Path

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from app.db.migrations import INITIAL_REVISION, alembic_config, upgrade_to_head
from app.schemas.domain import FeatureRead, RunRead

DOMAIN_TABLES = {"data_versions", "connections", "task_specs", "runs", "features", "llm_calls"}
INITIAL_TABLES = {"users", "projects", "datasets", "experiments", "hypotheses", "model_artifacts"}


def _url(path: Path) -> str:
    return f"sqlite+aiosqlite:///{path}"


def _tables(path: Path) -> set[str]:
    with sqlite3.connect(path) as conn:
        rows = conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
    return {r[0] for r in rows} - {"sqlite_sequence"}


def _columns(path: Path, table: str) -> set[str]:
    with sqlite3.connect(path) as conn:
        return {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}


def _insert_sample_rows(path: Path) -> None:
    now = datetime.now(UTC).isoformat()
    with sqlite3.connect(path) as conn:
        conn.execute(
            "INSERT INTO users (id, email, is_active, created_at, updated_at) VALUES (?,?,?,?,?)",
            ("u1", "a@example.com", 1, now, now),
        )
        conn.execute(
            "INSERT INTO projects (id, name, task_type, status, owner_id, created_at, updated_at)"
            " VALUES (?,?,?,?,?,?,?)",
            ("p1", "Churn", "classification", "active", "u1", now, now),
        )
        for i in range(3):
            conn.execute(
                "INSERT INTO experiments (id, project_id, dataset_version, hypothesis,"
                " change_description, model_name, parameters, validation_config,"
                " preprocessing_config, feature_set, budget, artifacts, metrics, status, decision,"
                " created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    f"e{i}",
                    "p1",
                    "v1",
                    "h",
                    "c",
                    "LGBMClassifier",
                    '{"seed": 42}',
                    "{}",
                    "{}",
                    "[]",
                    "{}",
                    "[]",
                    '{"f1": 0.5}',
                    "completed",
                    "keep",
                    now,
                    now,
                ),
            )


def test_upgrade_head_then_downgrade_base_on_a_fresh_file(tmp_path):
    db = tmp_path / "fresh.db"
    cfg = alembic_config(_url(db))
    command.upgrade(cfg, "head")
    assert INITIAL_TABLES | DOMAIN_TABLES <= _tables(db)
    assert {"run_id", "data_version_id", "decision_mode"} <= _columns(db, "experiments")
    command.downgrade(cfg, "base")
    assert _tables(db) == {"alembic_version"}


def test_initial_schema_with_rows_upgrades_without_losing_them(tmp_path):
    db = tmp_path / "old.db"
    cfg = alembic_config(_url(db))
    command.upgrade(cfg, INITIAL_REVISION)
    _insert_sample_rows(db)
    command.upgrade(cfg, "head")
    with sqlite3.connect(db) as conn:
        assert conn.execute("SELECT count(*) FROM experiments").fetchone()[0] == 3
        assert conn.execute(
            "SELECT metrics, parameters FROM experiments WHERE id='e1'"
        ).fetchone() == (
            '{"f1": 0.5}',
            '{"seed": 42}',
        )
        assert conn.execute("SELECT settings FROM projects WHERE id='p1'").fetchone() == ("{}",)


def test_database_made_before_migrations_is_stamped_and_upgraded(tmp_path):
    db = tmp_path / "legacy.db"
    command.upgrade(alembic_config(_url(db)), INITIAL_REVISION)
    _insert_sample_rows(db)
    with sqlite3.connect(db) as conn:  # what the old start-up code left behind
        conn.execute("DROP TABLE alembic_version")
    upgrade_to_head(_url(db))
    assert DOMAIN_TABLES <= _tables(db)
    with sqlite3.connect(db) as conn:
        assert conn.execute("SELECT count(*) FROM experiments").fetchone()[0] == 3
        assert conn.execute("SELECT version_num FROM alembic_version").fetchone() == ("0002",)


def test_upgrade_to_head_is_idempotent(tmp_path):
    db = tmp_path / "twice.db"
    upgrade_to_head(_url(db))
    upgrade_to_head(_url(db))
    assert DOMAIN_TABLES <= _tables(db)


def test_models_and_migrations_agree(tmp_path):
    """A model change without a migration fails here (same check as `alembic check`)."""
    cfg = alembic_config(_url(tmp_path / "check.db"))
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as e:  # pragma: no cover - the failure message is the point
        pytest.fail(f"models differ from migrations; run `alembic revision --autogenerate`: {e}")


def test_app_code_never_creates_tables_from_metadata():
    app_dir = Path(__file__).resolve().parents[2] / "app"
    offenders = [p for p in app_dir.rglob("*.py") if "create_all" in p.read_text()]
    assert offenders == []


def test_read_schemas_accept_orm_rows():
    from app.db.models import Feature, Run

    now = datetime.now(UTC)
    run = Run(
        id="r1",
        project_id="p1",
        engine="LGBMClassifier",
        seed=42,
        status="created",
        split_plan={},
        budget={},
        budget_used={},
        created_at=now,
    )
    feat = Feature(
        id="f1",
        run_id="r1",
        name="orders_30d",
        kind="llm_sql",
        status="proposed",
        sql="SELECT 1",
        created_at=now,
    )
    assert RunRead.model_validate(run).engine == "LGBMClassifier"
    assert FeatureRead.model_validate(feat).kind == "llm_sql"
