"""StubProvider — works fully offline with no API keys.

Returns deterministic, structured placeholder responses for all task types.
Always registered as the last-resort fallback in AIGateway.
"""
from __future__ import annotations

import json
from typing import Any, Optional

from ml.core.interfaces import AIProvider, ModelInfo

_STUB_RESPONSES = {
    "format": "[STUB] Formatted output.",
    "summarize": "[STUB] Summary: The data shows moderate class balance with some missing values. No critical leakage detected.",
    "hypothesize": "[STUB] Hypothesis: Adding polynomial features for numeric columns may improve model performance by capturing non-linear relationships.",
    "analyze": "[STUB] Analysis: Experiment shows a +2.3% improvement in F1 score over baseline. Precision improved but recall slightly decreased.",
    "synthesize": "[STUB] Synthesis: Three experiments show consistent improvement when using gradient boosting with depth=6 and learning_rate=0.05.",
    "report": "[STUB] Report: Project completed 5 experiments. Best model: XGBClassifier with F1=0.847. Recommended for deployment.",
    "decide": "[STUB] Decision: KEEP. The challenger experiment shows statistically meaningful improvement on the primary metric.",
    "default": "[STUB] Response generated by MLPilot StubProvider (offline mode).",
}

_STUB_MODELS = [
    ModelInfo(
        name="stub-default",
        provider="stub",
        context_window=8192,
        cost_per_1k_prompt_tokens=0.0,
        cost_per_1k_completion_tokens=0.0,
        capabilities=["complete", "structured", "format", "summarize", "hypothesize", "analyze", "report", "decide"],
        is_free=True,
    )
]


class StubProvider(AIProvider):
    """Offline stub AI provider for testing and development.

    Features:
    - No API key required
    - Deterministic responses keyed by task type
    - Supports structured output (returns valid JSON)
    - Zero cost
    - Always passes health_check()
    """

    name = "stub"
    default_model = "stub-default"

    async def complete(
        self,
        prompt: str,
        system: str = "",
        model: Optional[str] = None,
        max_tokens: int = 1024,
        temperature: float = 0.7,
    ) -> str:
        """Return a deterministic stub response."""
        # Detect task type from system or prompt
        text = (system + " " + prompt).lower()
        for key in _STUB_RESPONSES:
            if key in text:
                return _STUB_RESPONSES[key]
        return _STUB_RESPONSES["default"]

    async def complete_structured(
        self,
        prompt: str,
        schema: dict[str, Any],
        system: str = "",
        model: Optional[str] = None,
        max_tokens: int = 2048,
    ) -> dict[str, Any]:
        """Return a stub structured response matching the schema keys."""
        # Build a minimal dict matching the schema
        result: dict[str, Any] = {}
        properties = schema.get("properties", {})
        for key, prop in properties.items():
            prop_type = prop.get("type", "string")
            if prop_type == "string":
                result[key] = f"[STUB] {key}"
            elif prop_type == "number" or prop_type == "integer":
                result[key] = 0
            elif prop_type == "boolean":
                result[key] = False
            elif prop_type == "array":
                result[key] = []
            elif prop_type == "object":
                result[key] = {}
            else:
                result[key] = None
        return result

    def estimate_cost(
        self,
        prompt_tokens: int,
        completion_tokens: int,
        model: Optional[str] = None,
    ) -> float:
        """Always returns 0.0 — stub is free."""
        return 0.0

    async def list_models(self) -> list[ModelInfo]:
        return list(_STUB_MODELS)

    async def health_check(self) -> bool:
        """Always healthy — no network required."""
        return True
