import { execFileSync } from 'node:child_process';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

/** A DuckDB copy of the demo database, generated by the backend's own fixture (needs the dev dependencies). */
export function demoDuckdb(): string {
  const python = process.env.PYTHON ?? 'python';
  const dir = mkdtempSync(join(tmpdir(), 'mlpilot-e2e-'));
  const path = join(dir, 'demo.duckdb');
  execFileSync(
    python,
    ['-c', 'import sys; from pathlib import Path; from tests.fixtures.demo_db import demo_duckdb; demo_duckdb(Path(sys.argv[1]))', path],
    { cwd: join(process.cwd(), '..', 'backend'), stdio: 'inherit' },
  );
  return path;
}
