"""Cached column statistics of connected tables (#96)

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-06 22:41:19.146253
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table_stats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("table_key", sa.String(length=512), nullable=False),
        sa.Column("cache_key", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_table_stats_connection_id_connections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_table_stats")),
        sa.UniqueConstraint(
            "connection_id", "table_key", name=op.f("uq_table_stats_connection_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("table_stats")
    # ### end Alembic commands ###
