"""Schema overrides on connections (#45)

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 22:09:17.945576
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("schema_overrides", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connections", schema=None) as batch_op:
        batch_op.drop_column("schema_overrides")

    # ### end Alembic commands ###
